export const CREATE_TODO_LOADING = 'CREATE_TODO_LOADING';
export const CREATE_TODO_SUCCESSFULLY = 'CREATE_TODO_SUCCESSFULLY';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

export const START_DOWNLOAD_TODOS = 'START_DOWNLOAD_TODOS';
export const DOWNLOAD_TODOS_SUCCESSFULLY = 'DOWNLOAD_TODOS_SUCCESSFULLY';
export const DOWNLOAD_TODOS_ERROR = 'DOWNLOAD_TODOS_ERROR';

export const GET_TODO_DELETE = 'GET_TODO_DELETE';
export const TODO_DELETE_SUCCESSFULLY = 'TODO_DELETE_SUCCESSFULLY';
export const TODO_DELETE_ERROR = 'TODO_DELETE_ERROR';